import React from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { 
  Users, 
  Brain, 
  Video, 
  MessageCircle, 
  Trophy, 
  Clock,
  BookOpen,
  Zap,
  Star,
  ArrowRight,
  Play,
  CheckCircle
} from 'lucide-react';

import Button from '../components/common/Button';
import Card from '../components/common/Card';
import { useTheme } from '../contexts/ThemeContext';

/**
 * Modern, engaging landing page for Scramble
 * Features hero section, benefits, features, testimonials, and CTA
 */
const LandingPage = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: <Users className="w-8 h-8" />,
      title: 'Study Rooms',
      description: 'Create or join study groups with friends and classmates',
      color: 'soft-purple',
    },
    {
      icon: <Brain className="w-8 h-8" />,
      title: 'AI Quiz Generation',
      description: 'Get personalized quizzes generated by AI on any topic',
      color: 'vibrant-orange',
    },
    {
      icon: <Video className="w-8 h-8" />,
      title: 'Video Meetings',
      description: 'Built-in video calls with screen sharing and whiteboard',
      color: 'info-blue',
    },
    {
      icon: <MessageCircle className="w-8 h-8" />,
      title: 'Smart Chat',
      description: 'Rich messaging with LaTeX math, code snippets, and files',
      color: 'success-green',
    },
    {
      icon: <Trophy className="w-8 h-8" />,
      title: 'Gamification',
      description: 'Earn XP, badges, and climb leaderboards while studying',
      color: 'warm-yellow',
    },
    {
      icon: <Clock className="w-8 h-8" />,
      title: 'Study Timer',
      description: 'Pomodoro timer with analytics to track your focus',
      color: 'warning-red',
    },
  ];

  const benefits = [
    'Study together with friends from anywhere',
    'Get instant help with doubts and questions',
    'Track your progress with detailed analytics',
    'Stay motivated with gamification features',
    'Access AI-powered study tools',
    'Join a community of learners',
  ];

  const testimonials = [
    {
      name: 'Sarah Chen',
      role: 'Computer Science Student',
      avatar: 'https://via.placeholder.com/60/ff5734/ffffff?text=SC',
      quote: 'Scramble transformed how I study! The AI quizzes are incredibly helpful, and studying with friends makes it so much more engaging.',
      rating: 5,
    },
    {
      name: 'Marcus Johnson',
      role: 'Pre-Med Student',
      avatar: 'https://via.placeholder.com/60/be94f5/ffffff?text=MJ',
      quote: 'The doubt system is a game-changer. I get answers to my questions so quickly, and helping others reinforces my own learning.',
      rating: 5,
    },
    {
      name: 'Emma Rodriguez',
      role: 'Engineering Student',
      avatar: 'https://via.placeholder.com/60/fccc42/000000?text=ER',
      quote: 'Love the study rooms! Our group meets virtually every day, and the leaderboard keeps us all motivated to study more.',
      rating: 5,
    },
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.5,
        ease: 'easeOut',
      },
    },
  };

  return (
    <div className="min-h-screen bg-cool-blue-gray">
      {/* Navigation */}
      <nav className="container-app py-6">
        <div className="flex items-center justify-between">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center space-x-2"
          >
            <div className="w-10 h-10 bg-gradient-to-br from-vibrant-orange to-soft-purple rounded-xl flex items-center justify-center">
              <BookOpen className="w-6 h-6 text-white" />
            </div>
            <span className="text-2xl font-bold text-primary-black">Scramble</span>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center space-x-4"
          >
           
            <Button
              variant="ghost"
              onClick={() => navigate('/auth')}
            >
              Sign In
            </Button>
            <Button
              variant="primary"
              onClick={() => navigate('/auth')}
            >
              Get Started
            </Button>
          </motion.div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="container-app py-20">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="text-center max-w-4xl mx-auto"
        >
          <motion.h1
            variants={itemVariants}
            className="text-5xl md:text-6xl font-bold text-primary-black mb-6 leading-tight"
          >
            Study Together,{' '}
            <span className="text-gradient">Achieve Together</span>
          </motion.h1>

          <motion.p
            variants={itemVariants}
            className="text-xl text-muted-gray mb-8 leading-relaxed max-w-2xl mx-auto"
          >
            Join the modern collaborative study platform where students connect, 
            learn, and excel together. Make studying social, engaging, and effective.
          </motion.p>

          <motion.div
            variants={itemVariants}
            className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12"
          >
            <Button
              variant="primary"
              size="lg"
              onClick={() => navigate('/auth')}
              rightIcon={<ArrowRight size={20} />}
            >
              Start Studying Now
            </Button>
            <Button
              variant="ghost"
              size="lg"
              leftIcon={<Play size={20} />}
            >
              Watch Demo
            </Button>
          </motion.div>

          {/* Hero Image/Animation */}
          <motion.div
            variants={itemVariants}
            className="relative"
          >
            <div className="bg-gradient-to-br from-vibrant-orange to-soft-purple rounded-2xl p-8 shadow-card-xl">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-white">
                <div className="text-center">
                  <Users className="w-8 h-8 mx-auto mb-2" />
                  <div className="text-2xl font-bold">10K+</div>
                  <div className="text-sm opacity-90">Students</div>
                </div>
                <div className="text-center">
                  <Brain className="w-8 h-8 mx-auto mb-2" />
                  <div className="text-2xl font-bold">50K+</div>
                  <div className="text-sm opacity-90">Quizzes</div>
                </div>
                <div className="text-center">
                  <Clock className="w-8 h-8 mx-auto mb-2" />
                  <div className="text-2xl font-bold">100K+</div>
                  <div className="text-sm opacity-90">Study Hours</div>
                </div>
                <div className="text-center">
                  <Trophy className="w-8 h-8 mx-auto mb-2" />
                  <div className="text-2xl font-bold">95%</div>
                  <div className="text-sm opacity-90">Success Rate</div>
                </div>
              </div>
            </div>
          </motion.div>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="container-app py-20">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <motion.h2
            variants={itemVariants}
            className="text-4xl font-bold text-primary-black mb-4"
          >
            Everything You Need to Study Better
          </motion.h2>
          <motion.p
            variants={itemVariants}
            className="text-xl text-muted-gray max-w-2xl mx-auto"
          >
            Powerful features designed to make collaborative learning fun, 
            engaging, and effective for modern students.
          </motion.p>
        </motion.div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
        >
          {features.map((feature, index) => (
            <motion.div key={index} variants={itemVariants}>
              <Card hoverable className="h-full text-center">
                <div className={`w-16 h-16 bg-${feature.color} bg-opacity-10 rounded-2xl flex items-center justify-center mx-auto mb-4`}>
                  <div className={`text-${feature.color}`}>
                    {feature.icon}
                  </div>
                </div>
                <h3 className="text-xl font-semibold text-primary-black mb-3">
                  {feature.title}
                </h3>
                <p className="text-muted-gray leading-relaxed">
                  {feature.description}
                </p>
              </Card>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* Benefits Section */}
      <section className="container-app py-20">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h2 className="text-4xl font-bold text-primary-black mb-6">
              Why Students Love Scramble
            </h2>
            <p className="text-xl text-muted-gray mb-8 leading-relaxed">
              Join thousands of students who have transformed their study habits 
              and achieved better results through collaborative learning.
            </p>
            
            <div className="space-y-4">
              {benefits.map((benefit, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className="flex items-center space-x-3"
                >
                  <CheckCircle className="w-6 h-6 text-success-green flex-shrink-0" />
                  <span className="text-primary-black font-medium">{benefit}</span>
                </motion.div>
              ))}
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 50 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="relative"
          >
            <Card variant="gradient" className="p-8">
              <div className="text-white">
                <Zap className="w-12 h-12 mb-4" />
                <h3 className="text-2xl font-bold mb-4">Boost Your Grades</h3>
                <p className="text-lg opacity-90 mb-6">
                  Students using Scramble see an average improvement of 23% in their grades 
                  within the first semester.
                </p>
                <div className="grid grid-cols-2 gap-4 text-center">
                  <div>
                    <div className="text-3xl font-bold">23%</div>
                    <div className="text-sm opacity-80">Grade Improvement</div>
                  </div>
                  <div>
                    <div className="text-3xl font-bold">4.8★</div>
                    <div className="text-sm opacity-80">Student Rating</div>
                  </div>
                </div>
              </div>
            </Card>
          </motion.div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="container-app py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-bold text-primary-black mb-4">
            What Students Say
          </h2>
          <p className="text-xl text-muted-gray max-w-2xl mx-auto">
            Don't just take our word for it. Here's what real students say about Scramble.
          </p>
        </motion.div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-1 md:grid-cols-3 gap-8"
        >
          {testimonials.map((testimonial, index) => (
            <motion.div key={index} variants={itemVariants}>
              <Card hoverable className="h-full">
                <div className="flex items-center mb-4">
                  <img
                    src={testimonial.avatar}
                    alt={testimonial.name}
                    className="w-12 h-12 rounded-full mr-4"
                  />
                  <div>
                    <h4 className="font-semibold text-primary-black">
                      {testimonial.name}
                    </h4>
                    <p className="text-sm text-muted-gray">
                      {testimonial.role}
                    </p>
                  </div>
                </div>
                
                <div className="flex mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 text-warm-yellow fill-current" />
                  ))}
                </div>
                
                <p className="text-muted-gray leading-relaxed italic">
                  "{testimonial.quote}"
                </p>
              </Card>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* CTA Section */}
      <section className="container-app py-20">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <Card variant="gradient" className="max-w-4xl mx-auto text-center text-white">
            <h2 className="text-4xl font-bold mb-4">
              Ready to Transform Your Study Experience?
            </h2>
            <p className="text-xl opacity-90 mb-8 max-w-2xl mx-auto">
              Join thousands of students who are already studying smarter, 
              not harder. Get started with Scramble today!
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                variant="secondary"
                size="lg"
                onClick={() => navigate('/auth')}
                className="bg-white text-primary-black hover:bg-gray-100"
                rightIcon={<ArrowRight size={20} />}
              >
                Start Free Today
              </Button>
              <Button
                variant="ghost"
                size="lg"
                className="text-white border-white hover:bg-white hover:text-primary-black"
              >
                Learn More
              </Button>
            </div>
            
            <p className="text-sm opacity-75 mt-6">
              Free forever • No credit card required • Join in 30 seconds
            </p>
          </Card>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="container-app py-12 border-t border-muted-gray border-opacity-20">
        <div className="text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <div className="w-8 h-8 bg-gradient-to-br from-vibrant-orange to-soft-purple rounded-lg flex items-center justify-center">
              <BookOpen className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold text-primary-black">Scramble</span>
          </div>
          <p className="text-muted-gray mb-4">
            Made with ❤️ by students, for students
          </p>
          <p className="text-sm text-muted-gray">
            © 2024 Scramble. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;